using System.Runtime.InteropServices;
using System.Text;

namespace Anka.LoadTest;

/// <summary>
/// Writes a self-contained Markdown benchmark report to
/// <c>docs/throughput-results-{os}-{date}.md</c> relative to the solution root.
/// Each run produces a new file; existing results are never overwritten.
/// </summary>
internal static class ReportWriter
{
    public static void Write(
        string solutionRoot,
        IReadOnlyList<ServerBenchmarkResult> benchmarkRuns,
        int durationSeconds)
    {
        var docsDir = Path.Combine(solutionRoot, "docs");
        Directory.CreateDirectory(docsDir);
        var osSuffix = RuntimeInformation.IsOSPlatform(OSPlatform.Windows) ? "windows"
                     : RuntimeInformation.IsOSPlatform(OSPlatform.OSX)     ? "macos"
                     :                                                         "linux";
        var dateSuffix = DateTime.UtcNow.ToString("yyyy-MM-dd");
        var outPath = Path.Combine(docsDir, $"throughput-results-{osSuffix}-{dateSuffix}.md");

        var sb = new StringBuilder();

        WriteHeader(sb, durationSeconds);
        WriteEnvironment(sb, benchmarkRuns);
        WriteStartupSection(sb, benchmarkRuns);
        sb.AppendLine();

        sb.AppendLine("## Part 1 — Framework Tests");
        sb.AppendLine();
        sb.AppendLine("> No database. Measures raw HTTP pipeline throughput.");
        sb.AppendLine();

        foreach (var run in benchmarkRuns)
        {
            sb.AppendLine($"### {run.Target.Name} ({run.Target.RuntimeDescription})");
            sb.AppendLine();

            foreach (var (scenario, results) in run.FrameworkData)
            {
                WriteScenarioSection(sb, scenario, results);
            }
        }

        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## Part 2 — TechEmpower-Style DB Tests");
        sb.AppendLine();
        sb.AppendLine("> PostgreSQL backend. Mirrors the TechEmpower Framework Benchmarks test types.");
        sb.AppendLine();

        foreach (var run in benchmarkRuns)
        {
            sb.AppendLine($"### {run.Target.Name} ({run.Target.RuntimeDescription})");
            sb.AppendLine();

            foreach (var (scenario, results) in run.DbData)
            {
                WriteScenarioSection(sb, scenario, results);
            }
        }

        WriteFooter(sb);

        File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        Console.WriteLine($"\n📄  Report written → {outPath}");
    }

    private static void WriteHeader(StringBuilder sb, int duration)
    {
        sb.AppendLine("# Anka vs Kestrel — End-to-End Throughput Results");
        sb.AppendLine();
        sb.AppendLine("> Generated by `Anka.Wrk.LoadTest` using **[wrk](https://github.com/wg/wrk)**.");
        sb.AppendLine($"> Each scenario was run for **{duration} seconds** per concurrency level.");
        sb.AppendLine($"> Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void WriteEnvironment(StringBuilder sb, IReadOnlyList<ServerBenchmarkResult> benchmarkRuns)
    {
        sb.AppendLine("## Environment");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| OS | {RuntimeInformation.OSDescription} |");
        sb.AppendLine($"| Architecture | {RuntimeInformation.OSArchitecture} |");
        sb.AppendLine($"| .NET Runtime | {RuntimeInformation.FrameworkDescription} |");
        sb.AppendLine($"| Logical CPUs | {Environment.ProcessorCount} |");
        sb.AppendLine($"| Benchmarked servers | {string.Join(", ", benchmarkRuns.Select(run => $"{run.Target.Name} ({run.Target.RuntimeDescription})"))} |");
        sb.AppendLine($"| Database | PostgreSQL (TechEmpower-compatible schema) |");
        sb.AppendLine($"| Load generator | wrk (C, multi-threaded, keep-alive) |");
        sb.AppendLine();
        sb.AppendLine("> **Note:** Target servers and wrk ran on the same machine (loopback). Results reflect raw");
        sb.AppendLine("> server throughput; network latency is negligible at loopback speeds.");
    }

    private static void WriteStartupSection(StringBuilder sb, IReadOnlyList<ServerBenchmarkResult> benchmarkRuns)
    {
        sb.AppendLine();
        sb.AppendLine("## Startup & Cold-Start Snapshot");
        sb.AppendLine();
        sb.AppendLine("| Server | Runtime | Time to listen | Time to ready | First response | Startup alloc | RSS after first response |");
        sb.AppendLine("|---|---|---:|---:|---:|---:|---:|");

        foreach (var run in benchmarkRuns)
        {
            sb.AppendLine(
                $"| {run.Target.Name} " +
                $"| {run.Target.RuntimeDescription} " +
                $"| {FormatMs(run.Startup.TimeToListenMs),12} " +
                $"| {FormatMs(run.Startup.TimeToReadyMs),12} " +
                $"| {FormatMs(run.Startup.FirstResponseMs),12} " +
                $"| {FormatBytes(run.Startup.StartupAllocatedBytes),12} " +
                $"| {run.Startup.WorkingSetMb,8:F2} MB |");
        }

        sb.AppendLine();
    }

    private static void WriteScenarioSection(
        StringBuilder sb,
        Scenario scenario,
        IReadOnlyList<WrkResult> results)
    {
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine($"#### {scenario.Name}");
        sb.AppendLine();
        sb.AppendLine($"_{scenario.Description}_");
        sb.AppendLine();

        sb.AppendLine("| Connections | Req/sec | Avg Latency | P50 | P90 | P99 | P99.9 | Transfer/s | Errors |");
        sb.AppendLine("|---:|---:|---:|---:|---:|---:|---:|---:|---:|");

        foreach (var r in results)
        {
            sb.AppendLine(
                $"| {r.Connections,4} " +
                $"| {FormatRps(r.RequestsPerSec),10} " +
                $"| {FormatMs(r.LatencyAvgMs),11} " +
                $"| {FormatMs(r.P50Ms),8} " +
                $"| {FormatMs(r.P90Ms),8} " +
                $"| {FormatMs(r.P99Ms),8} " +
                $"| {FormatMs(r.P999Ms),8} " +
                $"| {r.TransferMbSec,8:F2} MB/s " +
                $"| {r.ErrorPct,6:F2}% |");
        }

        sb.AppendLine();
    }

    private static void WriteFooter(StringBuilder sb)
    {
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## Reproducing");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("# 1. Start PostgreSQL and create schema:");
        sb.AppendLine("psql -h localhost -U benchmarkdbuser -d hello_world -f Test/LoadTest/Anka.Wrk.LoadTest/scripts/setup_db.sql");
        sb.AppendLine();
        sb.AppendLine("# 2. Run the benchmark (DATABASE_URL defaults to localhost if unset):");
        sb.AppendLine("dotnet run --project Test/LoadTest/Anka.Wrk.LoadTest --configuration Release");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("Dependencies: [wrk](https://github.com/wg/wrk) must be on `PATH`.");
        sb.AppendLine("On macOS: `brew install wrk`. On Ubuntu: `apt install wrk`.");
    }

    // ── Formatting helpers ────────────────────────────────────────────────────

    private static string FormatRps(double rps)
    {
        return rps >= 1_000_000 ? $"{rps / 1_000_000:F2}M"
             : rps >= 1_000     ? $"{rps / 1_000:F1}k"
             :                    $"{rps:F0}";
    }

    private static string FormatMs(double ms)
    {
        return ms switch
        {
            <= 0   => "—",
            < 1    => $"{ms * 1000:F1} µs",
            < 1000 => $"{ms:F2} ms",
            _      => $"{ms / 1000:F2} s"
        };
    }

    private static string FormatBytes(long bytes)
    {
        return bytes switch
        {
            <= 0                => "—",
            < 1024              => $"{bytes} B",
            < 1024 * 1024       => $"{bytes / 1024.0:F1} KB",
            _                   => $"{bytes / (1024.0 * 1024.0):F2} MB"
        };
    }
}
