using System.Runtime.InteropServices;
using System.Text;

namespace Anka.LoadTest;

/// <summary>
/// Writes a self-contained Markdown benchmark report to <c>docs/throughput-results.md</c>
/// relative to the solution root that is passed in.
/// </summary>
internal static class ReportWriter
{
    public static void Write(
        string            solutionRoot,
        IReadOnlyList<(Scenario Scenario, IReadOnlyList<WrkResult> Results)> ankaData,
        IReadOnlyList<(Scenario Scenario, IReadOnlyList<WrkResult> Results)>? kestrelData,
        int[]             concurrencyLevels,
        int               durationSeconds)
    {
        var docsDir = Path.Combine(solutionRoot, "docs");
        Directory.CreateDirectory(docsDir);
        var outPath = Path.Combine(docsDir, "throughput-results.md");

        var sb = new StringBuilder();

        WriteHeader(sb, durationSeconds);
        WriteEnvironment(sb);
        sb.AppendLine();

        // ── Anka results ──────────────────────────────────────────────────────
        sb.AppendLine("## Anka (Native AOT)");
        sb.AppendLine();
        foreach (var (scenario, results) in ankaData)
        {
            WriteScenario(sb, scenario, results, concurrencyLevels);
        }

        // ── Kestrel results ───────────────────────────────────────────────────
        if (kestrelData is not null)
        {
            sb.AppendLine("## Kestrel (JIT self-contained)");
            sb.AppendLine();
            foreach (var (scenario, results) in kestrelData)
            {
                WriteScenario(sb, scenario, results, concurrencyLevels);
            }

            WriteComparison(sb, ankaData, kestrelData, concurrencyLevels);
        }

        WriteInterpretation(sb);
        WriteFooter(sb, durationSeconds);

        File.WriteAllText(outPath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
        Console.WriteLine($"\n📄  Report written → {outPath}");
    }
    
    private static void WriteHeader(StringBuilder sb, int duration)
    {
        sb.AppendLine("# Anka — End-to-End Throughput Results");
        sb.AppendLine();
        sb.AppendLine("> Generated by `Anka.Wrk.LoadTest` using **[wrk](https://github.com/wg/wrk)**.");
        sb.AppendLine($"> Each scenario was run for **{duration} seconds** per concurrency level.");
        sb.AppendLine($"> Date: {DateTime.UtcNow:yyyy-MM-dd HH:mm} UTC");
        sb.AppendLine();
        sb.AppendLine("---");
        sb.AppendLine();
    }

    private static void WriteEnvironment(StringBuilder sb)
    {
        sb.AppendLine("## Environment");
        sb.AppendLine();
        sb.AppendLine("| Property | Value |");
        sb.AppendLine("|---|---|");
        sb.AppendLine($"| OS | {RuntimeInformation.OSDescription} |");
        sb.AppendLine($"| Architecture | {RuntimeInformation.OSArchitecture} |");
        sb.AppendLine($"| .NET Runtime | {RuntimeInformation.FrameworkDescription} |");
        sb.AppendLine($"| Logical CPUs | {Environment.ProcessorCount} |");
        sb.AppendLine($"| Anka.HttpConsole | Release build, single process |");
        sb.AppendLine($"| Load generator | wrk (C, multi-threaded, keep-alive) |");
        sb.AppendLine();
        sb.AppendLine("> **Note:** Anka.HttpConsole and wrk ran on the same machine (loopback). Results reflect raw");
        sb.AppendLine("> server throughput; network latency is negligible at loopback speeds.");
    }

    private static void WriteScenario(
        StringBuilder sb,
        Scenario scenario,
        IReadOnlyList<WrkResult> results,
        int[] concurrencyLevels)
    {
        sb.AppendLine($"## Scenario: {scenario.Name}");
        sb.AppendLine();
        sb.AppendLine($"_{scenario.Description}_");
        sb.AppendLine();
        sb.AppendLine("```");
        sb.AppendLine($"wrk -t4 -c{{N}} -d10s --latency {results[0].Url}");
        sb.AppendLine("```");
        sb.AppendLine();

        sb.AppendLine("| Connections | Req/sec | Avg Latency | P90 | P99 | Transfer/s | Errors |");
        sb.AppendLine("|---:|---:|---:|---:|---:|---:|---:|");

        foreach (var r in results)
        {
            sb.AppendLine(
                $"| {r.Connections,4} " +
                $"| {FormatRps(r.RequestsPerSec),10} " +
                $"| {FormatMs(r.LatencyAvgMs),11} " +
                $"| {FormatMs(r.P90Ms),8} " +
                $"| {FormatMs(r.P99Ms),8} " +
                $"| {r.TransferMbSec,8:F2} MB/s " +
                $"| {r.ErrorPct,6:F2}% |");
        }

        sb.AppendLine();
    }

    private static void WriteComparison(
        StringBuilder sb,
        IReadOnlyList<(Scenario Scenario, IReadOnlyList<WrkResult> Results)> ankaData,
        IReadOnlyList<(Scenario Scenario, IReadOnlyList<WrkResult> Results)> kestrelData,
        int[] concurrencyLevels)
    {
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## Anka vs Kestrel — Side-by-Side Comparison");
        sb.AppendLine();
        sb.AppendLine("> **Ratio** = Anka req/s ÷ Kestrel req/s. Values > 1.0× mean Anka is faster.");
        sb.AppendLine();

        for (var i = 0; i < ankaData.Count && i < kestrelData.Count; i++)
        {
            var (scenario, ankaResults)    = ankaData[i];
            var (_, kestrelResults) = kestrelData[i];

            sb.AppendLine($"### {scenario.Name}");
            sb.AppendLine();
            sb.AppendLine("| Connections | Anka req/s | Kestrel req/s | Ratio | Anka P99 | Kestrel P99 |");
            sb.AppendLine("|---:|---:|---:|---:|---:|---:|");

            for (var j = 0; j < ankaResults.Count && j < kestrelResults.Count; j++)
            {
                var a = ankaResults[j];
                var k = kestrelResults[j];
                var ratio = k.RequestsPerSec > 0 ? a.RequestsPerSec / k.RequestsPerSec : 0;

                sb.AppendLine(
                    $"| {a.Connections,4} " +
                    $"| {FormatRps(a.RequestsPerSec),10} " +
                    $"| {FormatRps(k.RequestsPerSec),10} " +
                    $"| {ratio,6:F2}× " +
                    $"| {FormatMs(a.P99Ms),8} " +
                    $"| {FormatMs(k.P99Ms),8} |");
            }

            sb.AppendLine();
        }
    }

    private static void WriteInterpretation(StringBuilder sb)
    {
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## How to Interpret These Results");
        sb.AppendLine();
        sb.AppendLine("| Metric | What it measures |");
        sb.AppendLine("|---|---|");
        sb.AppendLine("| **Req/sec** | Peak throughput — how many complete HTTP/1.1 request–response cycles Anka finishes per second. Higher is better. |");
        sb.AppendLine("| **Avg Latency** | Mean time from request sent to first byte of response received. Lower is better. |");
        sb.AppendLine("| **P90 / P99** | 90th / 99th percentile latency. P99 captures tail latency — the worst 1 in 100 requests. |");
        sb.AppendLine("| **Transfer/s** | Network throughput in MB/s (headers + body). Useful for comparing response-size scenarios. |");
        sb.AppendLine("| **Errors** | Non-2xx responses or connection failures as a percentage of total requests sent. |");
        sb.AppendLine();
        sb.AppendLine("### Scaling pattern");
        sb.AppendLine();
        sb.AppendLine("Anka uses a **fire-and-forget task per connection** model: the accept loop never blocks.");
        sb.AppendLine("Throughput therefore scales with connection count until the CPU or OS scheduler saturates.");
        sb.AppendLine("The \"sweet spot\" is typically where Req/sec plateaus — adding more connections after that");
        sb.AppendLine("increases latency without improving throughput.");
        sb.AppendLine();
        sb.AppendLine("### Key design properties visible in the numbers");
        sb.AppendLine();
        sb.AppendLine("- **Zero heap allocation per request** — `ArrayPool<byte>` + `HttpRequestPool` CAS slot keeps");
        sb.AppendLine("  GC pressure flat even at high concurrency.");
        sb.AppendLine("- **Single `SendAsync` for small bodies** (≤ 4 KB) — headers and body are written into one");
        sb.AppendLine("  rented buffer, producing a single syscall. The *Large Response* scenario triggers the");
        sb.AppendLine("  two-`SendAsync` path.");
        sb.AppendLine("- **HTTP/1.1 keep-alive** — wrk reuses connections; all measured latency is pure");
        sb.AppendLine("  server-processing time, not TCP handshake overhead.");
        sb.AppendLine();
    }

    private static void WriteFooter(StringBuilder sb, int duration)
    {
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("## Reproducing");
        sb.AppendLine();
        sb.AppendLine("```bash");
        sb.AppendLine("# From the repository root:");
        sb.AppendLine("dotnet run --project Anka.Wrk.LoadTest --configuration Release");
        sb.AppendLine("```");
        sb.AppendLine();
        sb.AppendLine("Dependencies: [wrk](https://github.com/wg/wrk) must be on `PATH`.");
        sb.AppendLine("On macOS: `brew install wrk`. On Ubuntu: `apt install wrk`.");
    }

    // ── Formatting helpers ────────────────────────────────────────────────────

    private static string FormatRps(double rps)
    {
        return rps >= 1_000_000 ? $"{rps / 1_000_000:F2}M"
             : rps >= 1_000     ? $"{rps / 1_000:F1}k"
             :                    $"{rps:F0}";
    }

    private static string FormatMs(double ms)
    {
        return ms switch
        {
            <= 0   => "—",
            < 1    => $"{ms * 1000:F1} µs",
            < 1000 => $"{ms:F2} ms",
            _      => $"{ms / 1000:F2} s"
        };
    }
}
